Aula 4 - Extração de Características

EX 1 - BOW

In [1]:
from sklearn. feature_extraction.text import CountVectorizer

documentos = [
  "gato e cachorro",
  "gato brinca com cachorro",
  "gato e rato"
]

vectorizer = CountVectorizer()

X = vectorizer. fit_transform(documentos)
# fit >>> cria um vocabulário das palavras
# transforme >>> conta a frequencia de cada palavra no corpus

print(f"Vocabulario: {vectorizer. vocabulary_}")

print("Matriz BoW:")
print (X. toarray())

Vocabulario: {'gato': 3, 'cachorro': 1, 'brinca': 0, 'com': 2, 'rato': 4}
Matriz BoW:
[[0 1 0 1 0]
 [1 1 1 1 0]
 [0 0 0 1 1]]


EX 2 - BOW com TF-IDF

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

documentos = [
  "O cachorro gosta de passear no parque",
  "O gato dorme no sofá o dia todo",
  "Cachorros e gatos podem ser bons amigos"
]

#BOW
vectorizer_bow = CountVectorizer()
x_bow = vectorizer_bow.fit_transform(documentos)

print(f"Vocabulario BoW: {vectorizer_bow. vocabulary_}")
print("Matriz BoW:")
print(x_bow.toarray())

#BOW+TF-IDF
vectorizer_tfidf = TfidfVectorizer()
x_tfidf = vectorizer_tfidf.fit_transform(documentos)

print(f"\nVocabulario TF-IDF: {vectorizer_tfidf.vocabulary_}")
print("Matriz TF-IDF")
print(x_tfidf.toarray())

Vocabulario BoW: {'cachorro': 2, 'gosta': 9, 'de': 4, 'passear': 12, 'no': 10, 'parque': 11, 'gato': 7, 'dorme': 6, 'sofá': 15, 'dia': 5, 'todo': 16, 'cachorros': 3, 'gatos': 8, 'podem': 13, 'ser': 14, 'bons': 1, 'amigos': 0}
Matriz BoW:
[[0 0 1 0 1 0 0 0 0 1 1 1 1 0 0 0 0]
 [0 0 0 0 0 1 1 1 0 0 1 0 0 0 0 1 1]
 [1 1 0 1 0 0 0 0 1 0 0 0 0 1 1 0 0]]

Vocabulario TF-IDF: {'cachorro': 2, 'gosta': 9, 'de': 4, 'passear': 12, 'no': 10, 'parque': 11, 'gato': 7, 'dorme': 6, 'sofá': 15, 'dia': 5, 'todo': 16, 'cachorros': 3, 'gatos': 8, 'podem': 13, 'ser': 14, 'bons': 1, 'amigos': 0}
Matriz TF-IDF
[[0.         0.         0.42339448 0.         0.42339448 0.
  0.         0.         0.         0.42339448 0.32200242 0.42339448
  0.42339448 0.         0.         0.         0.        ]
 [0.         0.         0.         0.         0.         0.42339448
  0.42339448 0.42339448 0.         0.         0.32200242 0.
  0.         0.         0.         0.42339448 0.42339448]
 [0.40824829 0.40824829 0.        

EX 4 - WordEmbedding com Word2VEX

In [7]:
from gensim.models import Word2Vec

corpus = [
  ["o","cachorro","está","dormindo"],
  ["o","gato","está","dormindo"]
]

model = Word2Vec(sentences=corpus, vector_size=100, window=5, min_count=1,sg=1)
# sentences = define o texto a ser transformado em vetor
# vector_size = define a dimensão dos vetores que representarão as palavras
# window = define a janela de contexto. considera as palavras antes e as palavras depois no alvo para aprender
# min_count = ignora as palavras que aparecer 1 vez no corpus
# indica o modelo utilizado
# 1 = skip_gram;
# 0 = CBOW

vector = model.wv['cachorro']

similarity = model.wv.similarity('cachorro','gato')

print("Similaridade entre 'cachorro' e 'gato': ", similarity)

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject

In [4]:
!pip install gensim

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.6/26.6 MB 58.3 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 60.6 MB/s eta 0:00:00:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.2/38.2 MB 59.8 MB/s eta 0:00:00:00:01
  Attempting uninstall: numpy
    Found existing installation: numpy 2.2.4
    Uninstalling numpy-2.2.4:
      Successfully uninstalled numpy-2.2.4
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.2
    Uninstalling scipy-1.15.2:
      Successfully uninstalled scipy-1.15.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.


In [6]:
from gensim.models import Word2Vec

corpus = [
  ["o", "cachorro", "está", "latindo", "no", "quintal"],
  ["o", "gato", "está", "miando", "no", "telhado"],
  ["o", "pássaro", "está", "voando", "no", "céu",'lua'],
  ["a", "bola", "está", "rolando", "no", "chão"],
  ["a", "criança", "está", "brincando", "com", "o", "cachorro"],
  ["o", "gato", "e", "o", "rato", "são", "inimigos"],
  ["a", "água", "está", "quente", "na", "caneca"],
  ["o", "sol", "está", "brilhando", "no", "céu"],
  ["a", "lua", "está", "cheia", "hoje",'no' , 'céu' ],
  ["a", "computador", "está", "ligado", "na", "mesa"],
  ['a','lua' ,'esta' , 'no' , 'ceu', 'lua' , 'bonita' ]
]

model = Word2Vec(sentences=corpus, vector_size=100, window=5, min_count=1, sg=1)

print(f"Similaridade entre cachorro e gato: {model.wv.similarity('cachorro', 'gato' ) }")
print(f"Similaridade entre cachorro e bola: {model.wv.similarity('cachorro', 'bola' ) }")
print(f"Similaridade entre céu e lua: {model.wv.similarity('ceu', 'lua' ) }")
print(f"Similaridade entre computador e mesa: {model.wv.similarity('computador', 'mesa' ) }")

ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject